name = "copebot"
main = "dist/index.ts"
env = { }
compatibility_date = "2025-08-13"

[triggers]
crons = [ ]

[vars]
BOT_DOMAIN = "https://copebot.mehrad77.workers.dev"
SECRET_PATH = "me"


[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
